-- Shared enum types and the updated_at trigger helper for the Cashero schema.

create type movement_kind as enum ('expense', 'income', 'transfer');

create type movement_origin as enum (
  'manual',              -- entered by the user
  'recurring',           -- generated from a movement template
  'month_close_surplus', -- generated by the automatic month close (surplus split)
  'month_close_deficit'  -- generated by the automatic month close (deficit cover)
);

create type category_kind as enum ('expense', 'income');

create type account_interest_type as enum ('simple', 'compound');

create type template_frequency as enum ('daily', 'weekly', 'monthly', 'yearly');

-- Keeps updated_at in sync on every UPDATE. Attached per-table below.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
